# Configuration for Alacritty, the GPU enhanced terminal emulator

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
    ]
live_config_reload = true

[window]
# Window dimensions (changes require restart)
dimensions = { columns = 120, lines = 35 }

# Window padding
padding = { x = 10, y = 10 }

# Window decorations
decorations = "Buttonless"

# Startup Mode (changes require restart)
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title.
dynamic_title = true

# Window opacity as a floating point number from 0.0 to 1.0
opacity = 0.80

[scrolling]
# Maximum number of lines in the scrollback buffer.
history = 10000

# Scrolling distance multiplier.
multiplier = 3


[font]
# Normal (roman) font face
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

# Point size
size = 14.0

# Offset is the extra space around each character
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }

[cursor]
# Cursor style
style = { shape = "Beam", blinking = "On" }

# Cursor blinking interval in milliseconds.
blink_interval = 750

# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
unfocused_hollow = true

# Thickness of the cursor relative to the cell width as floating point number
# from 0.0 to 1.0.
thickness = 0.1

[selection]
# This string contains all characters that are used as separators for
# "semantic words" in Alacritty.
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard = true


[keyboard]
# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "F"
mods = "Command|Control"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"
