set laststatus=2
set tabstop=2
set shiftwidth=2
set expandtab
set smarttab
so ~/.vim/plugins.vim
set nocompatible
set nobackup
set nowritebackup
set noswapfile
set wildmenu
set ruler
set hlsearch
set statusline+=%F
set incsearch
set showmatch
set smartindent
set autoindent
set nofoldenable
set foldmethod=indent
set clipboard=unnamed
set completeopt=menuone,longest
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
"let g:alduin_Shout_Become_Ethereal = 1
set number
set mouse+=a
syn on
set termguicolors
set linespace=3
set guifont=Fira\ Code:h12
set cursorline
set shell=/bin/zsh
syntax enable
"set cursorcolumn

"====SETTING FOR GRUVBOX====="
let g:enable_italic_font = 1
let g:enable_bold_font = 1
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_termcolors=16
"============================"

"colorscheme molokai
"colorscheme alduin
"colorscheme jellybeans
"colorscheme badwolf
"colorscheme hybrid_reverse
"colorscheme solarflare
"colorscheme gruvbox
"colorscheme heroku-contrast
colorscheme hybrid
set background=dark

let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 1


"======SETTING FOR JELLYBEANS COLORSCHEME===="
let g:jellybeans_use_lowcolor_black = 0
let g:jellybeans_use_term_italics = 1
"======================================="

hi Normal guibg=black ctermbg=NONE
map <C-n> :NERDTreeToggle<CR>
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-f> :NERDTreeFind<CR>
" Switch between different windows by their direction`
noremap <S-Down> <C-w>j
noremap <S-Up> <C-w>k
noremap <S-Right> <C-w>l
noremap <S-Left> <C-w>h
" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
let g:molokai_original = 1
set lazyredraw
set synmaxcol=180
set ttyfast

"=====KEY BINDINGS======="
nnoremap <C-k> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>
" Comment line(s)
:vnoremap <C-c> :norm i#<CR>
" Uncomment line(s)
:vnoremap <C-l> :norm ^x<CR>
"========================"

if has("autocmd")
  filetype plugin indent on
endif

autocmd FileType * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd FileType * match Error /\s\+$/


"=====SYNTASTIC CONFIG===="
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
" (Optional)Remove Info(Preview) window
set completeopt-=preview
" (Optional)Hide Info(Preview) window after completions
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

"" (Optional) Enable terraform plan to be include in filter
"let g:syntastic_terraform_tffilter_plan = 1
"
"" (Optional) Default: 0, enable(1)/disable(0) plugin's keymapping
"let g:terraform_completion_keys = 1
"
"" (Optional) Default: 1, enable(1)/disable(0) terraform module registry completion
"let g:terraform_registry_module_completion = 1
"========================"

set runtimepath+=~/.vim/plugged/deoplete.nvim

filetype plugin indent on
"----------------------------------------------------------
" Neovim's Python provider
"----------------------------------------------------------

